definitions:
  handler.signup:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  shema.Login:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /answers/:
    get:
      consumes:
      - application/json
      description: Вопросы
      parameters:
      - description: ID
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses: {}
      summary: Answers
      tags:
      - Answers
  /answers/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: value
        required: true
        schema:
          type: string
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: AddAnswers
      tags:
      - Answers
  /answers/delete:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: string
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: AnswersDelete
      tags:
      - Answers
  /answers/put:
    put:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: value
        required: true
        schema:
          type: string
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: UpdateAnswers
      tags:
      - Answers
  /blockquiz/:
    get:
      consumes:
      - application/json
      description: Блоки опросов
      parameters:
      - description: ID
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses: {}
      summary: BlockQuiz
      tags:
      - BlockQuiz
  /blockquiz/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: value
        required: true
        schema:
          type: string
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: AddBlockQuiz
      tags:
      - BlockQuiz
  /blockquiz/delete:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: string
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: BlockQuizDelete
      tags:
      - BlockQuiz
  /blockquiz/put:
    put:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: value
        required: true
        schema:
          type: string
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: UpdateBlockQuiz
      tags:
      - BlockQuiz
  /cause/:
    get:
      consumes:
      - application/json
      description: Вопросы
      parameters:
      - description: ID
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses: {}
      summary: Cause
      tags:
      - Cause
  /cause/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: value
        required: true
        schema:
          type: string
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: AddCause
      tags:
      - Cause
  /cause/delete:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: string
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: CauseDelete
      tags:
      - Cause
  /cause/put:
    put:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: value
        required: true
        schema:
          type: string
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: UpdateCause
      tags:
      - Cause
  /login:
    post:
      consumes:
      - application/json
      description: login
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/shema.Login'
      produces:
      - application/json
      responses: {}
      summary: SignIn
      tags:
      - Auth
  /questions/:
    get:
      consumes:
      - application/json
      description: Вопросы
      parameters:
      - description: ID
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses: {}
      summary: Questions
      tags:
      - Questions
  /questions/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: value
        required: true
        schema:
          type: string
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: AddQuestions
      tags:
      - Questions
  /questions/delete:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: string
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: QuestionsDelete
      tags:
      - Questions
  /questions/put:
    put:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: value
        required: true
        schema:
          type: string
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: UpdateQuestions
      tags:
      - Questions
  /quiz/:
    get:
      consumes:
      - application/json
      description: Опрос
      parameters:
      - description: ID
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses: {}
      summary: Quiz
      tags:
      - Quiz
  /quiz/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: value
        required: true
        schema:
          type: string
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: AddQuiz
      tags:
      - Quiz
  /quiz/delete:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: string
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: QuizDelete
      tags:
      - Quiz
  /quiz/put:
    put:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: value
        required: true
        schema:
          type: string
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: UpdateQuiz
      tags:
      - Quiz
  /result/:
    get:
      consumes:
      - application/json
      description: Вопросы
      parameters:
      - description: ID
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses: {}
      summary: Result
      tags:
      - Result
  /result/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: value
        required: true
        schema:
          type: string
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: AddResult
      tags:
      - Result
  /result/delete:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: string
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: ResultDelete
      tags:
      - Result
  /result/put:
    put:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: value
        required: true
        schema:
          type: string
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: UpdateResult
      tags:
      - Result
  /signup:
    get:
      consumes:
      - application/json
      description: SignUp
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.signup'
      produces:
      - application/json
      responses: {}
      summary: SignUp
      tags:
      - Auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
